/* empty css                      */import{a as b,S as L,i as c}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const $="50640550-6e86534d3ec4691f775b301fd",w="https://pixabay.com/api/";async function p(o,t=1,s=15){const a=`${w}?key=${$}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${s}`;try{return(await b.get(a)).data}catch(e){throw console.error(e),e}}function f(o){return o.map(({webformatURL:t,largeImageURL:s,tags:a,likes:e,views:r,comments:l,downloads:g})=>`
    <a href="${s}" class="gallery__item">
      <img src="${t}" alt="${a}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${e}</p>
        <p><b>Views:</b> ${r}</p>
        <p><b>Comments:</b> ${l}</p>
        <p><b>Downloads:</b> ${g}</p>
      </div>
    </a>
  `).join("")}function E(o){o.innerHTML=""}const v=document.querySelector("#search-form"),y=document.querySelector(".gallery"),i=document.querySelector(".loader"),n=document.createElement("button");n.textContent="Load more";n.classList.add("load-more");n.style.display="none";document.body.appendChild(n);let m=new L(".gallery a"),d=1,h="",u=0;v.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements.searchQuery.value.trim();if(!t){c.error({title:"Error",message:"Search query cannot be empty!"});return}h=t,d=1,u=0,E(y),n.style.display="none",i.style.display="block";try{const s=await p(t,d);if(i.style.display="none",s.hits.length===0){c.warning({title:"No Results",message:"Sorry, there are no images matching your search query."});return}u=s.totalHits,y.innerHTML=f(s.hits),m.refresh(),n.style.display="block"}catch{i.style.display="none",c.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});n.addEventListener("click",async()=>{d+=1,i.style.display="block";try{const o=await p(h,d);i.style.display="none",y.insertAdjacentHTML("beforeend",f(o.hits)),m.refresh(),d*15>=u&&(n.style.display="none",c.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}));const{height:t}=y.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{i.style.display="none",c.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});
//# sourceMappingURL=index.js.map
